name: pr
on: [pull_request]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: # Set Azure credentials secret as an input
          credentials: ${{ secrets.DOCKERHUB_USERNAME }}
        env:
          credentials: ${{ secrets.DOCKERHUB_USERNAME }}
      - run: sh ./.github/scripts/test.sh
        env:
          TEST: ${{ secrets.DOCKERHUB_USERNAME }}